version: 2.1

executors:
    node-executor:
        docker:
            - image: cimg/node:18.17
        working_directory: ~/project

jobs:
    test:
        executor: node-executor
        steps:
            - checkout
            - run: npm install
            - run: npm test

workflows:
    version: 2
    test:
        jobs:
            - test